### ISSUE TITLE
Fix deployment or make it automatic

### ISSUE THREAD

**Issue by john-d-pelingo** [awnigharbia/filmy#30]
It looks like the website is still outdated https://awnigharbia.github.io/filmy/

**Comment by awnigharbia** [comment]
The latest version of `axios` is `0.21.4`.

Already upgraded.

**Comment by john-d-pelingo** [comment]
This is not related to `axios`. It's related to keeping your web app up to date. It doesn't have to be a CI/CD pipeline. You can make use of an `npm` script that you can run manually that deploys it to github pages.

**Comment by john-d-pelingo** [comment]
Solved now
